# Generated by Django 5.1 on 2024-09-29 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Title", models.CharField(max_length=150)),
                ("Description", models.TextField()),
                ("Due_Date", models.DateTimeField()),
                (
                    "PriorityLevel",
                    models.CharField(
                        choices=[
                            ("LOW", "Low"),
                            ("MEDIUM", "Medium"),
                            ("HIGH", "High"),
                        ],
                        default="LOW",
                        max_length=10,
                    ),
                ),
                (
                    "Status",
                    models.CharField(
                        choices=[("PENDING", "Pending"), ("COMPLETED", "Completed")],
                        default="PENDING",
                        max_length=10,
                    ),
                ),
            ],
        ),
    ]
