# Generated by Django 5.1 on 2024-10-01 06:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="task",
            options={"ordering": ["-DueDate"]},
        ),
        migrations.RenameField(
            model_name="task",
            old_name="Due_Date",
            new_name="DueDate",
        ),
        migrations.AddField(
            model_name="task",
            name="author",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="task",
            name="completed_at",
            field=models.DateTimeField(null=True),
        ),
    ]
