# Generated by Django 5.1.2 on 2024-10-15 22:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0004_taskhistory"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="taskhistory",
            options={"ordering": ["-completed_at"]},
        ),
    ]
