# Generated by Django 5.1.2 on 2024-10-18 11:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("categories", "0004_alter_category_name"),
        ("tasks", "0005_alter_taskhistory_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="tasks",
                to="categories.category",
            ),
        ),
    ]
