venv:
	source env/bin/activate

run:
	python manage.py runserver 5500

db:
	python manage.py makemigrations
	python manage.py migrate

test:
	python manage.py test

api_test:
	python manage.py test api